# Basic GitHub action pipeline to invoke the automation using GitHub Actions."
name: Invoke Automation Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Automation Repository
        uses: actions/checkout@v2
      - run: |
          ./scripts/RunExamplesStandalone.ps1
        shell: pwsh"
